# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/.ico/rake.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, -10, 881, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/logo-removebg-preview (1).png"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1050, 10, 171, 151))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 3), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 50px")
        self.pushButton.setIconSize(QtCore.QSize(150, 150))
        self.pushButton.setObjectName("pushButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(1730, 0, 271, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(20, 120, 640, 480))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("icons/walle_2.jpg"))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(630, 120, 640, 480))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/walle_2.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 580, 640, 480))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icons/walle_2.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(630, 580, 640, 480))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("icons/walle_2.jpg"))
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(1780, 150, 101, 31))
        self.progressBar.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.progressBar.setProperty("value", 50)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1260, 250, 756, 691))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(2, 0, 5, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_12 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout.addWidget(self.line_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.lineer_v = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lineer_v.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lineer_v.setObjectName("lineer_v")
        self.horizontalLayout.addWidget(self.lineer_v)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.angle_v = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.angle_v.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.angle_v.setObjectName("angle_v")
        self.horizontalLayout_4.addWidget(self.angle_v)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.roll = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.roll.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.roll.setObjectName("roll")
        self.horizontalLayout_3.addWidget(self.roll)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_31.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_3.addWidget(self.label_31)
        self.pitch = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pitch.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pitch.setObjectName("pitch")
        self.horizontalLayout_3.addWidget(self.pitch)
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_32.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_3.addWidget(self.label_32)
        self.yaw = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.yaw.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.yaw.setObjectName("yaw")
        self.horizontalLayout_3.addWidget(self.yaw)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setStyleSheet("font: 12.5pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.eksen_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eksen_1.setObjectName("eksen_1")
        self.horizontalLayout_5.addWidget(self.eksen_1)
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_35.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_5.addWidget(self.label_35)
        self.eksen_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eksen_2.setObjectName("eksen_2")
        self.horizontalLayout_5.addWidget(self.eksen_2)
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_36.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_5.addWidget(self.label_36)
        self.eksen_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eksen_3.setObjectName("eksen_3")
        self.horizontalLayout_5.addWidget(self.eksen_3)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_33.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_5.addWidget(self.label_33)
        self.eksen_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eksen_4.setObjectName("eksen_4")
        self.horizontalLayout_5.addWidget(self.eksen_4)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_34.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_5.addWidget(self.label_34)
        self.eksen_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eksen_5.setObjectName("eksen_5")
        self.horizontalLayout_5.addWidget(self.eksen_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.sol_rpm = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sol_rpm.setObjectName("sol_rpm")
        self.horizontalLayout_6.addWidget(self.sol_rpm)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.sag_rpm = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sag_rpm.setObjectName("sag_rpm")
        self.horizontalLayout_6.addWidget(self.sag_rpm)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(495, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_7.addWidget(self.horizontalSlider)
        self.horizontalSlider.setRange(27,300) #sıcaklık değeri
        self.horizontalSlider.setPageStep(5) #her bir tıkta 5 birim ilerler
        self.horizantalSlider.valueChanged.connect(self.updateTemp) #slider değişimini labela yazdırmak için fonksiyon çağırır
        sld2.setRange(0, 5)
        sld2.setPageStep(5)
        sld2.valueChanged.connect(self.updateLabel2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_27.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_11.addWidget(self.label_27)
        self.r_konum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.r_konum.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.r_konum.setObjectName("r_konum")
        self.horizontalLayout_11.addWidget(self.r_konum)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_11.addWidget(self.line_6)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_29.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_12.addWidget(self.label_29)
        self.flipper_a = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.flipper_a.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.flipper_a.setObjectName("flipper_a")
        self.horizontalLayout_12.addWidget(self.flipper_a)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout.addWidget(self.line_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_30.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_13.addWidget(self.label_30)
        self.co2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.co2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.co2.setObjectName("co2")
        self.horizontalLayout_13.addWidget(self.co2)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem20)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem21)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.line_10 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout.addWidget(self.line_10)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_37 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_37.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_14.addWidget(self.label_37)
        self.hava = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hava.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.hava.setObjectName("hava")
        self.horizontalLayout_14.addWidget(self.hava)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem22)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem23)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.line_11 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_38.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_15.addWidget(self.label_38)
        self.candela = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.candela.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.candela.setObjectName("candela")
        self.horizontalLayout_15.addWidget(self.candela)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem24)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem25)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.line_13 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout.addWidget(self.line_13)
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(1780, 210, 101, 31))
        self.timeEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.timeEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhTime)
        self.timeEdit.setObjectName("timeEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1260, 210, 161, 33))
        self.label_6.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(630, 120, 395, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setAcceptDrops(False)
        self.pushButton_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 120, 395, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_8.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(20, 580, 395, 32))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_19.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_19.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_19.addWidget(self.pushButton_9)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(630, 580, 395, 32))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_21.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_21.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_21.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(1240, 160, 141, 41))
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 3), stop:1 rgba(255, 255, 255, 255));\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border-radius: 50px")
        self.pushButton_13.setObjectName("pushButton_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rake Gui"))
        self.pushButton.setText(_translate("MainWindow", "EMERGENCY\n"
"STOP!!\n"
""))
        self.commandLinkButton.setText(_translate("MainWindow", "2.Pencere Git"))
        self.label_8.setText(_translate("MainWindow", "Lineer Hız:"))
        self.lineer_v.setText(_translate("MainWindow", "- m/s"))
        self.label_11.setText(_translate("MainWindow", "Açısal Hız:"))
        self.angle_v.setText(_translate("MainWindow", "- m/s"))
        self.label_9.setText(_translate("MainWindow", "Oryantasyon:"))
        self.label_10.setText(_translate("MainWindow", "Roll:"))
        self.roll.setText(_translate("MainWindow", "-"))
        self.label_31.setText(_translate("MainWindow", "Pitch:"))
        self.pitch.setText(_translate("MainWindow", "-"))
        self.label_32.setText(_translate("MainWindow", "Yaw:"))
        self.yaw.setText(_translate("MainWindow", "-"))
        self.label_13.setText(_translate("MainWindow", "Kol Açıları"))
        self.label_14.setText(_translate("MainWindow", "e1:"))
        self.eksen_1.setText(_translate("MainWindow", "-"))
        self.label_35.setText(_translate("MainWindow", "e2:"))
        self.eksen_2.setText(_translate("MainWindow", "-"))
        self.label_36.setText(_translate("MainWindow", "e3:"))
        self.eksen_3.setText(_translate("MainWindow", "-"))
        self.label_33.setText(_translate("MainWindow", "e4:"))
        self.eksen_4.setText(_translate("MainWindow", "-"))
        self.label_34.setText(_translate("MainWindow", "e5:"))
        self.eksen_5.setText(_translate("MainWindow", "-"))
        self.label_16.setText(_translate("MainWindow", "Motor RPM Değerleri:"))
        self.label_18.setText(_translate("MainWindow", "Sol RPM:"))
        self.sol_rpm.setText(_translate("MainWindow", "-"))
        self.label_12.setText(_translate("MainWindow", "Sağ RPM"))
        self.sag_rpm.setText(_translate("MainWindow", "-"))
        self.label_17.setText(_translate("MainWindow", "Araç İçi Sıcaklık:"))
        self.label_27.setText(_translate("MainWindow", "Robot Konumu:"))
        self.r_konum.setText(_translate("MainWindow", "-"))
        self.label_29.setText(_translate("MainWindow", "Flipper Açıları:"))
        self.flipper_a.setText(_translate("MainWindow", "-"))
        self.label_30.setText(_translate("MainWindow", "CO2 Oranı:   "))
        self.co2.setText(_translate("MainWindow", "-"))
        self.label_37.setText(_translate("MainWindow", "Hava Kalitesi:"))
        self.hava.setText(_translate("MainWindow", "-"))
        self.label_38.setText(_translate("MainWindow", "Işık Şiddeti Mik.:"))
        self.candela.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "Robot Verileri"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_1.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_13.setText(_translate("MainWindow", "Değerleri Ata"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

